### ISSUE TITLE
Don't use catch (...)

### ISSUE THREAD

**Issue by johnwason** [tesseract-robotics/boost_plugin_loader#10]
Using `catch (...)` is a really bad idea. It can catch system exceptions that should not be caught. Either use `catch (std::exception&)`, or better yet use the `boost::dll` functions that have an error code `ec` parameter. These functions will not throw, instead they will set the `ec` parameter to `true` with an error code and description.

**Comment by Levi-Armstrong** [comment]
Address by PR #11
