### ISSUE TITLE
Example does not build on windows

### ISSUE THREAD

**Issue by Levi-Armstrong** [tesseract-robotics/boost_plugin_loader#2]
It looks like the variable `static const std::string section;` is not being exported in the dll causing linking error. I tried several things but not sure how to resolve the issue so the build of the example is disabled for windows.

**Comment by marip8** [comment]
Per our conversation, I think we can try changing this to a static function that returns a string instead of being a member variable

**Comment by Levi-Armstrong** [comment]
Switching to static method solved the issue!

**Comment by marip8** [comment]
Should we incorporate the example back into a unit test now? Or do you just want to keep it as an example?

**Comment by Levi-Armstrong** [comment]
That is up to you. I think either way we can reference as an example implementation.
